def main():
    return ValueError
x = main()
print(x)